name: automationCore
description: A bunch o' home automation
version: 0.0.1
homepage: https://isaacparker.co
author: isaac <parrotmac@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  mqtt_client: ^5.1.0
  path: ^1.4.1
  uuid: 2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
